/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrameVisual;

import Comun.Lectura;
import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class CargarDataSet extends javax.swing.JFrame {

    /**
     * Creates new form CargarDataSet
     */
    
    private Menu me;
    
    
    public CargarDataSet(Menu m) {
        initComponents();
        
           this.me = m;
        

        this.setLocation(400, 100);
        this.setTitle("CARGAR DATASET");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btberlin52 = new javax.swing.JButton();
        btcerrar = new javax.swing.JButton();
        btch130 = new javax.swing.JButton();
        btch150 = new javax.swing.JButton();
        btd493 = new javax.swing.JButton();
        btd657 = new javax.swing.JButton();
        btdsindice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btberlin52.setText("berlin52");
        btberlin52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btberlin52btBerlin52(evt);
            }
        });

        btcerrar.setText("Volver al Menu");
        btcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcerrarbtVolverMenu(evt);
            }
        });

        btch130.setText("ch130");
        btch130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btch130btCh130(evt);
            }
        });

        btch150.setText("ch150");
        btch150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btch150btCh150(evt);
            }
        });

        btd493.setText("d493");
        btd493.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btd493btD493(evt);
            }
        });

        btd657.setText("d657");
        btd657.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btd657btD657(evt);
            }
        });

        btdsindice.setText("DataSet con indice");
        btdsindice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdsindicebtDataSetIndice(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btch150, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btd493, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btdsindice)
                            .addComponent(btd657, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btch130, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btberlin52, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btcerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btberlin52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btd493, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btch130, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btd657, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btdsindice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btch150, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btberlin52btBerlin52(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btberlin52btBerlin52

            Menu.dataSetA = null;
            Menu.dataSetA = Lectura.leerFichero("berlin52.tsp");
            me.setLbDataSet("berlin52");
       
        this.setVisible(false);
    }//GEN-LAST:event_btberlin52btBerlin52

    private void btcerrarbtVolverMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcerrarbtVolverMenu
        this.setVisible(false);
    }//GEN-LAST:event_btcerrarbtVolverMenu

    private void btch130btCh130(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btch130btCh130

        
            Menu.dataSetA = null;
            Menu.dataSetA = Lectura.leerFichero("ch130.tsp");
            me.setLbDataSet("ch130");

        this.setVisible(false);
    }//GEN-LAST:event_btch130btCh130

    private void btch150btCh150(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btch150btCh150

        
            Menu.dataSetA = null;
            Menu.dataSetA = Lectura.leerFichero("ch150.tsp");
            me.setLbDataSet("ch150");

        this.setVisible(false);
    }//GEN-LAST:event_btch150btCh150

    private void btd493btD493(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btd493btD493


            Menu.dataSetA = null;
            Menu.dataSetA = Lectura.leerFichero("d493.tsp");
            me.setLbDataSet("d493");

        this.setVisible(false);
    }//GEN-LAST:event_btd493btD493

    private void btd657btD657(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btd657btD657

       
            Menu.dataSetA = null;
            Menu.dataSetA = Lectura.leerFichero("d657.tsp");
            me.setLbDataSet("g657");

        this.setVisible(false);
    }//GEN-LAST:event_btd657btD657

    private void btdsindicebtDataSetIndice(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdsindicebtDataSetIndice
        String s = JOptionPane.showInputDialog(this, "Dime la talla");

        if (!s.isEmpty()) {
            int i = Integer.valueOf(s);
            if (i > 0) {

                Lectura.generarDataSet(i, Menu.peorcaso);


                    Menu.dataSetA = null;
                    Menu.dataSetA = Lectura.leerFichero("DataSet" + i + ".tsp");
                    me.setLbDataSet("DataSet" + i);

                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Debes poner un numero entero mayor que 0", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes poner un numero entero mayor que 0", "AVISO", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btdsindicebtDataSetIndice


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btberlin52;
    private javax.swing.JButton btcerrar;
    private javax.swing.JButton btch130;
    private javax.swing.JButton btch150;
    private javax.swing.JButton btd493;
    private javax.swing.JButton btd657;
    private javax.swing.JButton btdsindice;
    // End of variables declaration//GEN-END:variables
}
