/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrameVisual;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import puntos.Punto;

/**
 *
 * @author jaime
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public static boolean peorcaso = false;
    public static ArrayList<Punto> dataSetA = null;

    private MainFrame mainF;

    public Menu(MainFrame F) {
        initComponents();

        mainF = F;

    }

    public void setLbDataSet(String s) {
        lbdsmemoria.setText(s);
    }

    public String getLbDataSet() {
        return lbdsmemoria.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ckpeorcaso = new javax.swing.JCheckBox();
        CargarDataSet = new javax.swing.JButton();
        ComprobarEstrategia = new javax.swing.JButton();
        lbtx1 = new javax.swing.JLabel();
        lbdsmemoria = new javax.swing.JLabel();
        btsalir = new javax.swing.JButton();
        ComprobarTodasEstrategias = new javax.swing.JButton();
        ComprobarDosEstrategias = new javax.swing.JButton();
        btgraficascoste = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbtitulo = new javax.swing.JLabel();
        lbtitulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(786, 400));

        ckpeorcaso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ckpeorcaso.setText("PEOR CASO");
        ckpeorcaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckpeorcasoActionPerformed(evt);
            }
        });

        CargarDataSet.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CargarDataSet.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jaime\\Desktop\\AMC_Practica1-master\\src\\main\\java\\Images\\carga-de-progreso (2).png")); // NOI18N
        CargarDataSet.setText("Cargar DataSet en Memoria");
        CargarDataSet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CargarDataSet.setPreferredSize(new java.awt.Dimension(175, 30));
        CargarDataSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarDataSet(evt);
            }
        });

        ComprobarEstrategia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ComprobarEstrategia.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jaime\\Desktop\\AMC_Practica1-master\\src\\main\\java\\Images\\cheque-doble.png")); // NOI18N
        ComprobarEstrategia.setText("Comprobar Estrategia");
        ComprobarEstrategia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ComprobarEstrategia.setPreferredSize(new java.awt.Dimension(175, 30));
        ComprobarEstrategia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprobarEstrategia(evt);
            }
        });

        lbtx1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbtx1.setText("DataSet cargado en memoria:");

        lbdsmemoria.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbdsmemoria.setText("null");

        btsalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btsalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jaime\\Desktop\\AMC_Practica1-master\\src\\main\\java\\Images\\salida.png")); // NOI18N
        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirbtSalir(evt);
            }
        });

        ComprobarTodasEstrategias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ComprobarTodasEstrategias.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jaime\\Desktop\\AMC_Practica1-master\\src\\main\\java\\Images\\comparar-codigo (2).png")); // NOI18N
        ComprobarTodasEstrategias.setText("Comparar todas las Estrategias");
        ComprobarTodasEstrategias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ComprobarTodasEstrategias.setPreferredSize(new java.awt.Dimension(175, 30));
        ComprobarTodasEstrategias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprobarTodasEstrategias(evt);
            }
        });

        ComprobarDosEstrategias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ComprobarDosEstrategias.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jaime\\Desktop\\AMC_Practica1-master\\src\\main\\java\\Images\\comparar-codigo (2).png")); // NOI18N
        ComprobarDosEstrategias.setText("Comparar 2 Estrategias");
        ComprobarDosEstrategias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ComprobarDosEstrategias.setPreferredSize(new java.awt.Dimension(175, 30));
        ComprobarDosEstrategias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprobarDosEstrategias(evt);
            }
        });

        btgraficascoste.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btgraficascoste.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jaime\\Desktop\\AMC_Practica1-master\\src\\main\\java\\Images\\mostrar-flecha-hacia-abajo.png")); // NOI18N
        btgraficascoste.setText("Mostrar Gráficas de Coste");
        btgraficascoste.setFocusable(false);
        btgraficascoste.setHideActionText(true);
        btgraficascoste.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btgraficascoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgraficascostebtGraficasCoste(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbtitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbtitulo.setText("Practica 1");

        lbtitulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbtitulo1.setText("ALGORTIMOS DE BUSQUEDA Y ORDENACION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lbtitulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbtitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbtitulo1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jaime\\Desktop\\AMC_Practica1-master\\src\\main\\java\\Images\\CVyU (1).gif")); // NOI18N

        jLabel2.setText("Rocio Pérez Holgado");

        jLabel3.setText("Alvaro Hernández ");

        jLabel4.setText("Jaime Garcia Marin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CargarDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(lbtx1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbdsmemoria))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ComprobarDosEstrategias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComprobarTodasEstrategias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComprobarEstrategia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btgraficascoste, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckpeorcaso))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CargarDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtx1)
                            .addComponent(lbdsmemoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComprobarEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckpeorcaso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComprobarTodasEstrategias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btgraficascoste, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ComprobarDosEstrategias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void CargarDataSet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDataSet
        CargarDataSet cds = new CargarDataSet(this);
        cds.setVisible(true);
    }//GEN-LAST:event_CargarDataSet

    private void ComprobarEstrategia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprobarEstrategia
        if (dataSetA != null) {
            ComprobarEstrategia cep = new ComprobarEstrategia(mainF, this);
            mainF.cambiarPanel(cep);
        } else {
            JOptionPane.showMessageDialog(this,
                    "El array cargado en memoria esta vacio, no se puede ejecutar",
                    "INFO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ComprobarEstrategia

    private void btsalirbtSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirbtSalir
        System.exit(0);
    }//GEN-LAST:event_btsalirbtSalir


    private void ComprobarTodasEstrategias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprobarTodasEstrategias
        ComprobarTodasEstrategias ctap = new ComprobarTodasEstrategias(mainF, this);
        mainF.cambiarPanel(ctap);
        
    }//GEN-LAST:event_ComprobarTodasEstrategias

    private void ComprobarDosEstrategias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprobarDosEstrategias

        CompararDosEstrategias cdep = new CompararDosEstrategias(mainF, this);
        mainF.cambiarPanel(cdep);
    }//GEN-LAST:event_ComprobarDosEstrategias

    private void btgraficascostebtGraficasCoste(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgraficascostebtGraficasCoste
        new MostrarGraficaCoste();
    }//GEN-LAST:event_btgraficascostebtGraficasCoste

    private void ckpeorcasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckpeorcasoActionPerformed
        if (peorcaso == false) {
            peorcaso = true;
            System.out.println("Peorcaso: " + peorcaso);
        } else {
            peorcaso = false;
            System.out.println("Peorcaso: " + peorcaso);
        }
    }//GEN-LAST:event_ckpeorcasoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarDataSet;
    private javax.swing.JButton ComprobarDosEstrategias;
    private javax.swing.JButton ComprobarEstrategia;
    private javax.swing.JButton ComprobarTodasEstrategias;
    private javax.swing.JButton btgraficascoste;
    private javax.swing.JButton btsalir;
    private javax.swing.JCheckBox ckpeorcaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbdsmemoria;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JLabel lbtitulo1;
    private javax.swing.JLabel lbtx1;
    // End of variables declaration//GEN-END:variables
}
